### PR TITLE
Fix compilation with the not yet released GCC 15

### LINKED ISSUE #1739: [Bug] Compile error with gcc-15
### Describe the problem

test compiling LE13 with gcc has identified some code compatibility and issues.

### Possible fix

_No response_

### Steps to reproduce

Compile with gcc-15-20241124

### Debug log

```
<<< inputstream.adaptive:target seq 381 <<<
BUILD      inputstream.adaptive (target)
    TOOLCHAIN      cmake (auto-detect)
Executing (target): cmake -GNinja -DCMAKE_EXPORT_COMPILE_COMMANDS=ON -DCMAKE_TOOLCHAIN_FILE=/var/media/DATA/home-rudi/LibreELEC.tv/build.LibreELEC-Generic.x86_64-13.0-devel/toolchain/etc/cmake-x86_64-libreelec-linux-gnu.conf -DCMAKE_INSTALL_PREFIX=/usr -DCMAKE_BUILD_TYPE=Release /var/media/DATA/home-rudi/LibreELEC.tv/build.LibreELEC-Generic.x86_64-13.0-devel/build/inputstream.adaptive-22.1.10-Piers
-- Found components for RapidJSON
-- RAPIDJSON_ROOT_DIR  = /var/media/DATA/home-rudi/LibreELEC.tv/build.LibreELEC-Generic.x86_64-13.0-devel/toolchain/x86_64-libreelec-linux-gnu/sysroot/usr
-- RAPIDJSON_INCLUDES  = /var/media/DATA/home-rudi/LibreELEC.tv/build.LibreELEC-Generic.x86_64-13.0-devel/toolchain/x86_64-libreelec-linux-gnu/sysroot/usr/include
CMake Deprecation Warning at lib/mpegts/CMakeLists.txt:1 (cmake_minimum_required):
  Compatibility with CMake < 3.10 will be removed from a future version of
  CMake.

  Update the VERSION argument <min> value.  Or, use the <min>...<max> syntax
  to tell CMake that the project requires at least <min> but has been updated
  to work with policies introduced by <max> or earlier.


CMake Deprecation Warning at lib/webm_parser/CMakeLists.txt:1 (cmake_minimum_required):
  Compatibility with CMake < 3.10 will be removed from a future version of
  CMake.

  Update the VERSION argument <min> value.  Or, use the <min>...<max> syntax
  to tell CMake that the project requires at least <min> but has been updated
  to work with policies introduced by <max> or earlier.


-- ADP_VERSION=22.1.10
-- Addon dependency check ...
--  - Added API usage definition: ADDON_GLOBAL_VERSION_MAIN_USED (Version: "2.0.2", Min. Version: "2.0.0")
--  - Added API usage definition: ADDON_GLOBAL_VERSION_GENERAL_USED (Version: "1.0.5", Min. Version: "1.0.4")
--  - Added API usage definition: ADDON_GLOBAL_VERSION_GUI_USED (Version: "5.15.1", Min. Version: "5.15.0")
--  - Added API usage definition: ADDON_GLOBAL_VERSION_FILESYSTEM_USED (Version: "1.1.9", Min. Version: "1.1.7")
--  - Added API usage definition: ADDON_GLOBAL_VERSION_TOOLS_USED (Version: "1.0.4", Min. Version: "1.0.0")
--  - Added API usage definition: ADDON_INSTANCE_VERSION_INPUTSTREAM_USED (Version: "3.3.0", Min. Version: "3.3.0")
--  - Added API usage definition: ADDON_INSTANCE_VERSION_VIDEOCODEC_USED (Version: "2.1.0", Min. Version: "2.1.0")
-- Configuring done (37.0s)
-- Generating done (0.1s)
-- Build files have been written to: /var/media/DATA/home-rudi/LibreELEC.tv/build.LibreELEC-Generic.x86_64-13.0-devel/build/inputstream.adaptive-22.1.10-Piers/.x86_64-libreelec-linux-gnu
Executing (target): ninja
[1/62] Building CXX object CMakeFiles/inputstream.adaptive.dir/src/main.cpp.o
FAILED: CMakeFiles/inputstream.adaptive.dir/src/main.cpp.o
/var/media/DATA/home-rudi/LibreELEC.tv/build.LibreELEC-Generic.x86_64-13.0-devel/toolchain/bin/x86_64-libreelec-linux-gnu-g++ -DADDON_GLOBAL_VERSION_FILESYSTEM_USED -DADDON_GLOBAL_VERSION_GENERAL_USED -DADDON_GLOBAL_VERSION_GUI_USED -DADDON_GLOBAL_VERSION_MAIN_USED -DADDON_GLOBAL_VERSION_TOOLS_USED -DADDON_INSTANCE_VERSION_INPUTSTREAM_USED -DADDON_INSTANCE_VERSION_VIDEOCODEC_USED -DBUILD_KODI_ADDON -D__STDC_FORMAT_MACROS -Dinputstream_adaptive_EXPORTS -I/var/media/DATA/home-rudi/LibreELEC.tv/build.LibreELEC-Generic.x86_64-13.0-devel/build/inputstream.adaptive-22.1.10-Piers/src -I/var/media/DATA/home-rudi/LibreELEC.tv/build.LibreELEC-Generic.x86_64-13.0-devel/build/inputstream.adaptive-22.1.10-Piers/lib/mpegts -I/var/media/DATA/home-rudi/LibreELEC.tv/build.LibreELEC-Generic.x86_64-13.0-devel/build/inputstream.adaptive-22.1.10-Piers/lib/webm_parser/include -I/var/media/DATA/home-rudi/LibreELEC.tv/build.LibreELEC-Generic.x86_64-13.0-devel/build/inputstream.adaptive-22.1.10-Piers/lib/cdm -march=x86-64-v3 -Wall -pipe  -O2 -fomit-frame-pointer -DNDEBUG -std=c++20 -fPIC   -DTARGET_POSIX -DTARGET_LINUX -D_GNU_SOURCE -DHAVE_LINUX_UDMABUF=1 -DHAVE_LINUX_DMA_HEAP=1 -DHAVE_LINUX_DMA_BUF=1 -DHAVE_MKOSTEMP=1 -DHAVE_LINUX_MEMFD=1 -DHAVE_STATX=1 -DHAVE_SSE=1 -DHAVE_SSE2=1 -DHAVE_SSE3=1 -DHAVE_SSSE3=1 -DHAVE_SSE4_1=1 -fvisibility=hidden -MD -MT CMakeFiles/inputstream.adaptive.dir/src/main.cpp.o -MF CMakeFiles/inputstream.adaptive.dir/src/main.cpp.o.d -o CMakeFiles/inputstream.adaptive.dir/src/main.cpp.o -c /var/media/DATA/home-rudi/LibreELEC.tv/build.LibreELEC-Generic.x86_64-13.0-devel/build/inputstream.adaptive-22.1.10-Piers/src/main.cpp
In file included from ../src/common/CommonAttribs.h:17,
                 from ../src/common/AdaptationSet.h:11,
                 from ../src/common/AdaptiveTree.h:12,
                 from ../src/Session.h:13,
                 from ../src/main.h:11,
                 from ../src/main.cpp:9:
/var/media/DATA/home-rudi/LibreELEC.tv/build.LibreELEC-Generic.x86_64-13.0-devel/toolchain/x86_64-libreelec-linux-gnu/include/c++/15.0.0/type_traits: In substitution of 'template<class _Up>  requires !(is_same_v<std::optional<_Tp>, typename std::remove_cvref<_It2>::type>) && !(is_same_v<std::in_place_t, typename std::remove_cvref<_It2>::type>) && (is_constructible_v<_Tp, _Up>) && (__not_constructing_bool_from_optional<_Up, typename std::remove_cv< <template-parameter-1-1> >::type>) constexpr std::optional<PLAYLIST::CSegmentList>::optional(_Up&&) [with _Up = PLAYLIST::CSegmentList]':
/var/media/DATA/home-rudi/LibreELEC.tv/build.LibreELEC-Generic.x86_64-13.0-devel/toolchain/x86_64-libreelec-linux-gnu/include/c++/15.0.0/type_traits:3547:46:   required from 'constexpr const bool std::is_constructible_v<PLAYLIST::CSegmentList, const PLAYLIST::CSegmentList&>'
 3547 |   inline constexpr bool is_constructible_v = __is_constructible(_Tp, _Args...);
      |                                              ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/var/media/DATA/home-rudi/LibreELEC.tv/build.LibreELEC-Generic.x86_64-13.0-devel/toolchain/x86_64-libreelec-linux-gnu/include/c++/15.0.0/optional:871:7:   required by substitution of 'template<class _Up>  requires !(is_same_v<std::optional<_Tp>, typename std::remove_cvref<_It2>::type>) && !(is_same_v<std::in_place_t, typename std::remove_cvref<_It2>::type>) && (is_constructible_v<_Tp, _Up>) && (__not_constructing_bool_from_optional<_Up, typename std::remove_cv< <template-parameter-1-1> >::type>) constexpr std::optional<PLAYLIST::CSegmentList>::optional(_Up&&) [with _Up = PLAYLIST::CSegmentList]'
  871 |           && is_constructible_v<_Tp, _Up>
      |              ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
../src/common/CommonSegAttribs.h:27:74:   required from here
   27 |   void SetSegmentList(const CSegmentList& segmentList) { m_segmentList = segmentList; }
      |                                                                          ^~~~~~~~~~~
/var/media/DATA/home-rudi/LibreELEC.tv/build.LibreELEC-Generic.x86_64-13.0-devel/toolchain/x86_64-libreelec-linux-gnu/include/c++/15.0.0/optional:874:2:   required by the constraints of 'template<class _Tp> template<class _Up>  requires !(is_same_v<std::optional<_Tp>, typename std::remove_cvref<_It2>::type>) && !(is_same_v<std::in_place_t, typename std::remove_cvref<_It2>::type>) && (is_constructible_v<_Tp, _Up>) && (__not_constructing_bool_from_optional<_Up, typename std::remove_cv< <template-parameter-1-1> >::type>) constexpr std::optional<_Tp>::optional(_Up&&)'
/var/media/DATA/home-rudi/LibreELEC.tv/build.LibreELEC-Generic.x86_64-13.0-devel/toolchain/x86_64-libreelec-linux-gnu/include/c++/15.0.0/optional:871:14: error: satisfaction of atomic constraint 'is_constructible_v<_Tp, _Up> [with _Tp = _Tp; _Up = _Up]' depends on itself
  871 |           && is_constructible_v<_Tp, _Up>
      |              ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
/var/media/DATA/home-rudi/LibreELEC.tv/build.LibreELEC-Generic.x86_64-13.0-devel/toolchain/x86_64-libreelec-linux-gnu/include/c++/15.0.0/type_traits: In substitution of 'template<class _Up>  requires !(is_same_v<std::optional<_Tp>, typename std::remove_cvref<_It2>::type>) && !(is_same_v<std::in_place_t, typename std::remove_cvref<_It2>::type>) && (is_constructible_v<_Tp, _Up>) && (__not_constructing_bool_from_optional<_Up, typename std::remove_cv< <template-parameter-1-1> >::type>) constexpr std::optional<PLAYLIST::CSegmentTemplate>::optional(_Up&&) [with _Up = PLAYLIST::CSegmentTemplate]':
/var/media/DATA/home-rudi/LibreELEC.tv/build.LibreELEC-Generic.x86_64-13.0-devel/toolchain/x86_64-libreelec-linux-gnu/include/c++/15.0.0/type_traits:3547:46:   required from 'constexpr const bool std::is_constructible_v<PLAYLIST::CSegmentTemplate, const PLAYLIST::CSegmentTemplate&>'
 3547 |   inline constexpr bool is_constructible_v = __is_constructible(_Tp, _Args...);
      |                                              ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/var/media/DATA/home-rudi/LibreELEC.tv/build.LibreELEC-Generic.x86_64-13.0-devel/toolchain/x86_64-libreelec-linux-gnu/include/c++/15.0.0/optional:871:7:   required by substitution of 'template<class _Up>  requires !(is_same_v<std::optional<_Tp>, typename std::remove_cvref<_It2>::type>) && !(is_same_v<std::in_place_t, typename std::remove_cvref<_It2>::type>) && (is_constructible_v<_Tp, _Up>) && (__not_constructing_bool_from_optional<_Up, typename std::remove_cv< <template-parameter-1-1> >::type>) constexpr std::optional<PLAYLIST::CSegmentTemplate>::optional(_Up&&) [with _Up = PLAYLIST::CSegmentTemplate]'
  871 |           && is_constructible_v<_Tp, _Up>
      |              ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
/var/media/DATA/home-rudi/LibreELEC.tv/build.LibreELEC-Generic.x86_64-13.0-devel/toolchain/x86_64-libreelec-linux-gnu/include/c++/15.0.0/type_traits:3623:7:   required from 'constexpr const bool std::is_nothrow_copy_constructible_v<PLAYLIST::CSegmentTemplate>'
 3623 |     = __is_nothrow_constructible(_Tp, __add_lval_ref_t<const _Tp>);
      |       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../src/common/CommonSegAttribs.h:31:71:   recursively required from 'constexpr std::optional<PLAYLIST::CSegmentTemplate>::optional(const std::optional<PLAYLIST::CSegmentTemplate>&)'
   31 |   std::optional<CSegmentTemplate> GetSegmentTemplate() const { return m_segmentTemplate; }
      |                                                                       ^~~~~~~~~~~~~~~~~
../src/common/CommonSegAttribs.h:31:71:   required from here
/var/media/DATA/home-rudi/LibreELEC.tv/build.LibreELEC-Generic.x86_64-13.0-devel/toolchain/x86_64-libreelec-linux-gnu/include/c++/15.0.0/optional:874:2:   required by the constraints of 'template<class _Tp> template<class _Up>  requires !(is_same_v<std::optional<_Tp>, typename std::remove_cvref<_It2>::type>) && !(is_same_v<std::in_place_t, typename std::remove_cvref<_It2>::type>) && (is_constructible_v<_Tp, _Up>) && (__not_constructing_bool_from_optional<_Up, typename std::remove_cv< <template-parameter-1-1> >::type>) constexpr std::optional<_Tp>::optional(_Up&&)'
```

### Stream manifest file(s)

_No response_

### Additional info

Using gcc15-20241124

### Operating system(s)

Linux

### Operating system version(s)

LibreELEC LE13 master

### InputStream Adaptive version(s)

22.1.10

### Kodi version(s)

Piers - 65703fe91c077d8cc11be4ba10221b56cd38d30b

### PR DESCRIPTION
**Pull request by neo1973**
## Description

Fix compilation with the not yet released GCC 15. Discussion and explanation of the change can be seen in #1739, specifically https://github.com/xbmc/inputstream.adaptive/issues/1739#issuecomment-2572231793.

## Motivation and context

Fixes #1739.

## How has this been tested?

It compiles :smile: 

## Types of change

- [X] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [ ] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **None of the above** (please explain below)

## Checklist:

- [X] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [X] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [ ] My change requires a change to the Wiki documentation
- [ ] I have updated the documentation accordingly

### CODE REVIEW

File: src/parser/DASHTree.cpp [hunk 1]
```diff
@@ -583,7 +583,10 @@ void adaptive::CDashTree::ParseTagAdaptationSet(pugi::xml_node nodeAdp, PLAYLIST
   xml_node nodeSegTpl = nodeAdp.child("SegmentTemplate");
   if (nodeSegTpl || period->HasSegmentTemplate())
   {
-    CSegmentTemplate segTemplate{period->GetSegmentTemplate()};
+    CSegmentTemplate segTemplate;
+    auto optSegTemplate = period->GetSegmentTemplate();
+    if (optSegTemplate)
+      segTemplate = std::move(*optSegTemplate);
```
Comment (CastagnaIT) [inline src/parser/DASHTree.cpp]: the initial intention about using constructor was to avoid all this verbose code, that result also repeated multiple times for each use

can you try add an assign operator method to the classes?
`CSegmentTemplate& operator=(const std::optional<CSegmentTemplate>& other)`
then should result as:
```
CSegmentTemplate segTemplate;
segTemplate = period->GetSegmentTemplate();
```
and see if compiler still cause problems?

Comment (neo1973) [reply src/parser/DASHTree.cpp]: That should work I think. But what are you opinions on the version I just pushed? Shorter and it makes it obvious that there maybe wasn't a value returned.

Comment (CastagnaIT) [reply src/parser/DASHTree.cpp]: very good! i didn't remember there was a builtin method, i will do a test soon as soon as i find some time

**Review by CastagnaIT — APPROVED** [review]
tested & debugged on windows lgtm thanks
