### PR TITLE
Set track id to actual

### LINKED ISSUE #853: Kodi 20: IA crashing with HGO streams on Android
Inputstream adaptive/Kodi is crashing in Kodi 20 with all streams from HGo (HBO) in Android (works on my other test machines which have linux). They play well under kodi 19 so its definitely some change in IA for nexus.
Can't tell much about the crash, the backtrace in logcat shows this:

```
12-11 19:19:16.481  8492  8492 D NowPlayingManager: onMediaDataUpdated: A notification for Now Playing Card has been posted with NowPlayingData [title=100 Foot Wave - 1 SEASON, EPISODE 2, artist=Unknown]
12-11 19:19:16.516 11679 11679 I chatty  : uid=10076(org.xbmc.kodi) expire 5 lines
12-11 19:19:16.594  3107  3107 I /system/bin/tombstoned: received crash request for pid 11644
12-11 19:19:16.649 11679 11679 F DEBUG   : *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
12-11 19:19:16.650 11679 11679 F DEBUG   : Build fingerprint: 'Xiaomi/oneday/oneday:9/PI/3595:user/release-keys'
12-11 19:19:16.650 11679 11679 F DEBUG   : Revision: '0'
12-11 19:19:16.650 11679 11679 F DEBUG   : ABI: 'arm'
12-11 19:19:16.650 11679 11679 F DEBUG   : pid: 11495, tid: 11644, name: Thread-14  >>> org.xbmc.kodi <<<
12-11 19:19:16.650 11679 11679 F DEBUG   : signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x0
12-11 19:19:16.650 11679 11679 F DEBUG   : Cause: null pointer dereference
12-11 19:19:16.650 11679 11679 F DEBUG   :     r0  00000000  r1  fffffff9  r2  ccd24510  r3  00000000
12-11 19:19:16.650 11679 11679 F DEBUG   :     r4  ccd24510  r5  00000000  r6  ced68ca4  r7  ced68c6c
12-11 19:19:16.650 11679 11679 F DEBUG   :     r8  f1bf9d8c  r9  75756964  r10 c9785d00  r11 ccd244b8
12-11 19:19:16.651 11679 11679 F DEBUG   :     ip  c55ea7d4  sp  ccd244b0  lr  c5554844  pc  c5555a50
12-11 19:19:16.717  4381  4381 I chromium: [4381:4381:INFO:metrics_recorder.cc(286)] cast event: Cloud.Transport.Https.StatusChange.Out.Success
12-11 19:19:16.816 11679 11679 F DEBUG   : 
12-11 19:19:16.816 11679 11679 F DEBUG   : backtrace:
12-11 19:19:16.817 11679 11679 F DEBUG   :     #00 pc 00112a50  /data/data/org.xbmc.kodi/cache/lib/libinputstream.adaptive.so
12-11 19:19:16.817 11679 11679 F DEBUG   :     #01 pc 000b035c  /data/data/org.xbmc.kodi/cache/lib/libinputstream.adaptive.so
12-11 19:19:16.817 11679 11679 F DEBUG   :     #02 pc 001124b8  /data/data/org.xbmc.kodi/cache/lib/libinputstream.adaptive.so
12-11 19:19:16.817 11679 11679 F DEBUG   :     #03 pc 00112674  /data/data/org.xbmc.kodi/cache/lib/libinputstream.adaptive.so
12-11 19:19:16.818 11679 11679 F DEBUG   :     #04 pc 001128e4  /data/data/org.xbmc.kodi/cache/lib/libinputstream.adaptive.so
12-11 19:19:16.818 11679 11679 F DEBUG   :     #05 pc 000af964  /data/data/org.xbmc.kodi/cache/lib/libinputstream.adaptive.so
12-11 19:19:16.818 11679 11679 F DEBUG   :     #06 pc 000a34ac  /data/data/org.xbmc.kodi/cache/lib/libinputstream.adaptive.so
12-11 19:19:16.818 11679 11679 F DEBUG   :     #07 pc 000a6188  /data/data/org.xbmc.kodi/cache/lib/libinputstream.adaptive.so
12-11 19:19:16.818 11679 11679 F DEBUG   :     #08 pc 012de214  /data/app/org.xbmc.kodi-ZPRQ-0226ZbSzQExF1iV-w==/lib/arm/libkodi.so (CDVDDemuxClient::Read()+92)
12-11 19:19:16.818 11679 11679 F DEBUG   :     #09 pc 01350d90  /data/app/org.xbmc.kodi-ZPRQ-0226ZbSzQExF1iV-w==/lib/arm/libkodi.so (CVideoPlayer::ReadPacket(DemuxPacket*&, CDemuxStream*&)+352)
12-11 19:19:16.818 11679 11679 F DEBUG   :     #10 pc 01352fa8  /data/app/org.xbmc.kodi-ZPRQ-0226ZbSzQExF1iV-w==/lib/arm/libkodi.so (CVideoPlayer::Process()+1024)
12-11 19:19:16.818 11679 11679 F DEBUG   :     #11 pc 01594b78  /data/app/org.xbmc.kodi-ZPRQ-0226ZbSzQExF1iV-w==/lib/arm/libkodi.so (CThread::Action()+40)
12-11 19:19:16.818 11679 11679 F DEBUG   :     #12 pc 01595048  /data/app/org.xbmc.kodi-ZPRQ-0226ZbSzQExF1iV-w==/lib/arm/libkodi.so
12-11 19:19:16.818 11679 11679 F DEBUG   :     #13 pc 01594f1c  /data/app/org.xbmc.kodi-ZPRQ-0226ZbSzQExF1iV-w==/lib/arm/libkodi.so
12-11 19:19:16.818 11679 11679 F DEBUG   :     #14 pc 01594d50  /data/app/org.xbmc.kodi-ZPRQ-0226ZbSzQExF1iV-w==/lib/arm/libkodi.so
12-11 19:19:16.818 11679 11679 F DEBUG   :     #15 pc 00063c15  /system/lib/libc.so (__pthread_start(void*)+22)
12-11 19:19:16.818 11679 11679 F DEBUG   :     #16 pc 0001e065  /system/lib/libc.so (__start_thread+22)
12-11 19:19:16.888  4381  4381 I chromium: [4381:4381:INFO:grpc_manager_impl.cc(495)] GRPC[uri=[::]:8012]: num_pending_calls=0, num_active_handlers=1, num_free_handlers=0
12-11 19:19:16.936  8492  8492 D NowPlayingListener: updateNowPlayingNotification with controller: NowPlayingMediaController {packageName = org.xbmc.kodi, state = 3, metadata = 100 Foot Wave - 1 SEASON, EPISODE 2, null, null}
12-11 19:19:16.936  8492  8492 D NowPlayingManager: onClientChanged() called with: clearing = [false]
```

Kodi debug logs:
Working (Kodi 19.3): https://paste.kodi.tv/hihofumiwe
Crashing (Kodi 20): https://paste.kodi.tv/vihicamima

Let me know if I can provide more info on the crash

### PR DESCRIPTION
**Pull request by glennguy**
## Description

If we have a 'made up' track id in the sample reader, sets this value to what the actual track id is.

## Motivation and context

ISM manifests (I'm no expert on this) seem to not have initialization segments specified - the init data is prefixed to each segment. IA deals with this by setting up a 'dummy' movie box and in the absence of a track id, sets it to a certain value.

## How has this been tested?

Tested with stream:
```
#KODIPROP:inputstream=inputstream.adaptive
#KODIPROP:inputstream.adaptive.manifest_type=ism
http://playready.directtaps.net/smoothstreaming/SSWSS720H264/SuperSpeedway_720.ism/Manifest
```

## What is the effect on users?

Fixes #853

## Types of change

- [x] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [ ] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **None of the above** (please explain below)

## Checklist:

- [x] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [x] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [ ] I have added tests to cover my change
- [x] All new and existing tests passed

### CODE REVIEW

File: src/main.cpp [hunk 1]
```diff
@@ -1375,12 +1375,34 @@ class ATTRIBUTE_HIDDEN FragmentedSampleReader : public SampleReader, public AP4_
   };
   uint32_t GetTimeScale() const override { return m_track->GetMediaTimeScale(); };
 
+public:
+  static const AP4_UI32 TRACKID_UNKNOWN = -1;
+
```
Comment (glennguy) [inline src/main.cpp:1380]: I've added the `public` again as I can see this convention further down for the private member variables in this class (only one public function above but it's several pages long). This should aid readability but my question is, is this right or not?

Comment (CastagnaIT) [reply src/main.cpp:1380]: i think that for now is ok
with the refactor related code i think will be moved under another file
then this variable can be moved in the header file as `constexpr`

**Review by CastagnaIT — APPROVED** [review]
