### PR TITLE
[AdaptiveStream] Rework to improve HLS manifest updates

### LINKED ISSUE #1109: Subtitles from German live broadcasters are not displayed in Kodi 20 (Nexus)
## Bug report
Subtitles from German live broadcasters (ARD, ZDF, etc.) are not displayed in Kodi 20 (Nexus), although selected in the OSD
### Describe the bug
It shows a single subtitle available: "German - Untertitel deutsch (Standard)" but nothing shows when it is turned on.

## Expected Behavior
Subtitles should be displayed on the screen

## Actual Behavior
Subtitles are not displayed in Kodi 20 (Nexus), although selected in the OSD

### To Reproduce

1. Call up the stream (using PVR IPTV Simple Client etc.) 
2. Enable subtitles via the OSD menu

### Debuglog

The debuglog can be found here:
[kodi_debug_nexus.log](https://github.com/xbmc/xbmc/files/10491763/kodi_debug_nexus.log)

### Screenshots
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:
Streaming Adresses of German live broadcasters (ZDF): 
https://zdf-hls-15.akamaized.net/hls/live/2016498/de/veryhigh/master.m3u8

### Your Environment
Used Operating system:

 - [x ] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: LineageOS 19 based on Android for Raspberry Pi 400
 - Kodi version: 20 (Nexus)

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

### LINKED ISSUE #1438: HLS live stream stops after several seconds in version 21.4.1
## Bug report
There seems to be a bug introduced with version 21.4.1 concerning playback of certain HLS streams. The stream starts but terminates after 10-60 seconds. With version 21.4.0 and the same configuration the same streams play without problems.
### Describe the bug

The stream is terminated and the last kodi screen appears. Streams of the same provider stop at different times but all within 1 minute.
The streams originate from a service provider in SEE. The streams are geoblocked and require a valid subscription. The addon which uses inputstream is a PVR addon. 

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

Expected behaviour is that the stream plays the same way as in previous version like 21.4.0

## Actual Behavior

Instead the stream terminates without user interaction

## Possible Fix

Maybe the changes between 21.4.0 and 21.4.1 concerning HLS (I can see two in the changelog) could be reverted.

### To Reproduce

1. Start stream from service provider
2. Wait for the crash

### Debuglog

The debuglog can be found here:
A debug log of the issue is here:
https://paste.kodi.tv/ugacunumad

### MPD/M3U8s/ISM

An example or copy of a manifest (or manifests for HLS - master and variants) can be found here:
Will be provided  in comments

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ x] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version: Omega Beta
 - inputstream.adaptive version: 21.4.1

*note: Once the issue is made we require you to update it with new information should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

### PR DESCRIPTION
**Pull request by CastagnaIT**
## Description

While was developing this i found many weirdness that i think are not new bugs,
most of these bugs can be reproduced by using "Stream selection" setting to "Test" by switching per 1 segment.
That could happens for example on live stream, that when switch quality kodi call OpenStream, but when AdaptiveStream::start_stream is called, dont find the next segment because not yet available and stop the playback wrongly....

One single time, i catched two kodi freeze/crash, when played "akmai" local stream:
1 case when doing video seek, two times, in fast way on the "same" point (with mouse)
1 case when stop playback
more likely i think are already existings bugs

PR Changes for live streams:
- HLS: Fix problem of playback stops after some time
- HLS: Fix playback stop with adaptive stream switching (not fully but much better than before)
- HLS: RAI live buzz sound mentioned in issue #1132 seem not happens anymore, and instead of buzz sound the stream pause for in right way buffering, but the workaround its still needed, to avoid better the buffer loading
- HLS: Fix child manifest subtitles still in download also when are disabled
- HLS: Fix subtitles segments not downloaded from new manifest updates (only show subtitles for first secs/segments) related to #1109

Unsolved bug was already existing:
if you play a HLS live stream with subtitles that are disabled,
when switch to a new period (DEMUX_SPECIALID_STREAMCHANGE) the subtitle stream will be re-enabled, this cause error
GenerateSidxSegments: [AS-20] Cannot generate segments
due to not downloaded child manifest

Unsolved bug i think was already existing:
Chapter change (DEMUX_SPECIALID_STREAMCHANGE) may be executed 2 times! by audio and video stream, i think due to slight differrent pts, could be?!, not easy to catch but its happened to me 1 or 2 times
idk if kodi expect one single chapter change?

~tomorrow i will comment some code parts... to give some details on code changes~ done

## Motivation and context

I have lost 2 weeks of nights on this also because its a big mess from old messy implementations and things that from my part i find difficult to learn how works

i think however that what i have done here should be better of what was there before and after estenuants tests seem almost stable, at least without hard use of adaptive streaming quality switching (on my tests always: "Test" mode per 1 segment)

fix #1438

this will fix also subtitles segment problem of #1109
where subtitles was displayed only for the first segments only and then stopped

## How has this been tested?

For multiperiod/chapters/ads:
Live Pluto TV i cant post the master manifest m3u8 link because expire after hours, but can be found on network flow of:
https://pluto.tv/en/live-tv/

http://mcdn.daserste.de/daserste/de/master.m3u8 (also for subs, not always there are news/tvshow)

"Akmai local stream"

Other live, no chapters:
https://cdndai.pl/tvp1hd/index.m3u8 (sometime the server may temporary ban your IP for ~30minuts)

RAI:
#KODIPROP:inputstream.adaptive.live_delay=30
https://mediapolis.rai.it/relinker/relinkerServlet.htm?cont=2606803&output=7

## Types of change

- [x] **Bug fix** (non-breaking change which fixes an issue)
- [x] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [ ] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **None of the above** (please explain below)

## Checklist:

- [ ] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [ ] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [ ] My change requires a change to the Wiki documentation
- [ ] I have updated the documentation accordingly

### CODE REVIEW

File: src/common/AdaptiveStream.cpp [hunk 1]
```diff
@@ -720,15 +722,32 @@ bool AdaptiveStream::start_stream(uint64_t startPts)
             current_rep_->get_segment(static_cast<size_t>(segmentId - current_rep_->GetStartNumber()));
       }
     }
+    else if (stream_changed_) // switching streams, align new stream segment no.
```
Comment (CastagnaIT) [inline src/common/AdaptiveStream.cpp:723]: I have lost most of the time due to this method AdaptiveStream::start_stream
because i was not aware that the AdaptiveStream::start_stream method is used to adjust/set the "current segment" and so all my changes that i was doing on ensure_segment always was failing.
After discovered this, i realized that was missing set "current segment" for a stream quality switching case

File: src/common/AdaptiveStream.cpp [hunk 2]
```diff
@@ -720,15 +722,32 @@ bool AdaptiveStream::start_stream(uint64_t startPts)
...
   const CSegment* next_segment =
       current_rep_->get_next_segment(current_rep_->current_segment_);
 
   if (!next_segment)
   {
+    //! @todo: THIS MUST BE CHANGED - !! BUG !!
+    //! this will broken/stop playback on live streams when adaptive stream change stream quality (so representation)
+    //! and there are no new segments because not immediately available (despite child manifest updated),
+    //! because we cant be ensure next segment without wait the appropriate timing...imo its not the right place here.
+    //! Can be reproduced with HLS live and by using "Stream selection" setting to "Test" by switching per 1 segment
```
Comment (CastagnaIT) [inline src/common/AdaptiveStream.cpp:750]: I also found this problem (read todo) i tried force remove this block of code that stop playback, and a bit below avoid set currentPTSOffset_ when there is no next_segment, playback works but show weird pts on Kodi GUI the value of time becomes sometimes negative and it can lead to weirdness in the long run.
Need to be changed on other way but idk atm, can be done separately, maybe can you help here

File: src/common/AdaptiveStream.cpp [hunk 3]
```diff
@@ -910,20 +930,25 @@ bool AdaptiveStream::ensureSegment()
           newRep = prevRep;
         else
           newRep = m_tree->GetRepChooser()->GetNextRepresentation(current_adp_, prevRep);
-      }
 
-      // If the representation has been changed, segments may have to be generated (DASH)
-      if (newRep->SegmentTimeline().IsEmpty())
-        GenerateSidxSegments(newRep);
-
-      if (!newRep->IsPrepared() && m_tree->SecondsSinceRepUpdate(newRep) > 1)
```
Comment (CastagnaIT) [inline src/common/AdaptiveStream.cpp:919]: On representation class `IsPrepared` and `m_isDownloaded` plus the `SecondsSinceRepUpdate` imo was really a mess of behaviours, i have removed them all, and add a new `IsNeedsUpdates`, used only internally in the HLSParser to distinguish whether a representation needs an update of some thing (in this case for live updates)

File: src/common/AdaptiveStream.cpp [hunk 4]
```diff
@@ -1212,17 +1238,22 @@ size_t adaptive::AdaptiveStream::getSegmentPos()
...
   if ((m_tree->HasManifestUpdates() || m_tree->HasManifestUpdatesSegs()) && state_ == RUNNING)
   {
     std::lock_guard<adaptive::AdaptiveTree::TreeUpdateThread> lckUpdTree(m_tree->GetTreeUpdMutex());
 
     if (current_rep_ && current_rep_->IsWaitForSegment())
     {
-      return !checkTime ||
-             (current_adp_->GetStreamType() != StreamType::VIDEO &&
-              current_adp_->GetStreamType() != StreamType::AUDIO) ||
-             SecondsSinceUpdate() < 1;
```
Comment (CastagnaIT) [inline src/common/AdaptiveStream.cpp:1224]: `SecondsSinceUpdate` uses (now removed) above and here should be the cause of the RAI buzz/frezze sound, by debugging this waitingForSegment method, was producing messed up return values

File: src/common/AdaptiveStream.cpp [hunk 5]
```diff
@@ -1212,17 +1238,22 @@ size_t adaptive::AdaptiveStream::getSegmentPos()
...
+      return !checkTime || (current_adp_->GetStreamType() != StreamType::VIDEO &&
+                            current_adp_->GetStreamType() != StreamType::AUDIO);
     }
+
+    // We can fall here when we are waiting for new segments, but the download it not started yet
+    // so return true only when checkTime is false, to avoid trigger EOS on sample reader and stop playback
+    return !checkTime;
```
Comment (CastagnaIT) [inline src/common/AdaptiveStream.cpp:1256]: This is the main cause because the Pluto TV stream was stopping playback (before was returning "false")

File: src/common/AdaptiveStream.cpp [hunk 6]
```diff
@@ -1289,16 +1320,15 @@ bool AdaptiveStream::GenerateSidxSegments(PLAYLIST::CRepresentation* rep)
...
-
   if (thread_data_)
   {
     thread_data_->Stop();
     StopWorker(STOPPED);
   }
+  // Disable representation only after stopped the worker
+  // otherwise if read some segments may invalidate this change
+  if (current_rep_)
+    current_rep_->SetIsEnabled(false);
```
Comment (CastagnaIT) [inline src/common/AdaptiveStream.cpp:1331]: Here the problem should be due to `AdaptiveStream::ensureSegment`
since force change `SetIsEnabled` on the representation and race condition may happens

File: src/common/Representation.h [hunk 7]
```diff
@@ -259,8 +257,7 @@ class ATTR_DLL_LOCAL CRepresentation : public CCommonSegAttribs, public CCommonA
   uint32_t assured_buffer_duration_{0};
   uint32_t max_buffer_duration_{0};
 
-  //! @todo: used for HLS only, not reflect the right meaning
-  bool m_isDownloaded{false};
+  uint64_t m_segPosition{SEGMENT_NO_NUMBER};
```
Comment (CastagnaIT) [inline src/common/Representation.h]: todo for me: remove me!

File: src/parser/DASHTree.cpp [hunk 8]
```diff
@@ -1552,7 +1552,6 @@ void adaptive::CDashTree::RefreshSegments(PLAYLIST::CPeriod* period,
 {
   if (adp->GetStreamType() == StreamType::VIDEO || adp->GetStreamType() == StreamType::AUDIO)
   {
-    m_updThread.ResetStartTime();
```
Comment (CastagnaIT) [inline src/parser/DASHTree.cpp:1555]: this should be a remnant of the old manifest update code, has no sense reset the worker thread here, isnt used when we update manifest at each new segment request "manually"

File: src/parser/HLSTree.cpp [hunk 9]
```diff
@@ -173,442 +173,469 @@ bool adaptive::CHLSTree::Open(std::string_view url,
   return true;
 }
 
-PLAYLIST::PrepareRepStatus adaptive::CHLSTree::prepareRepresentation(PLAYLIST::CPeriod* period,
-                                                                     PLAYLIST::CAdaptationSet* adp,
-                                                                     PLAYLIST::CRepresentation* rep,
-                                                                     bool update)
+bool adaptive::CHLSTree::PrepareRepresentation(PLAYLIST::CPeriod* period,
```
Comment (CastagnaIT) [inline src/parser/HLSTree.cpp:176]: Here github show a big mess on code diff, there are no functional code changes on PrepareRepresentation, the only difference is that has been decoupled per functionality.
The old `prepareRepresentation` now has been splitted on more methods:
- PrepareRepresentation: Act more or less as before
- DownloadChildManifest: To download the child manifest only
- ParseChildManifest: Parse the child manifest data
- PrepareSegments: Update the segments (to adjust/set "current segment")

now ParseChildManifest could be reused in future to parse in right way the media playlist on CHLSTree::ParseManifest (see todo), not tested now, but a step forward to achieve it

**Comment by CastagnaIT** [comment]
@glennguy when you will have time try test this PR and review
i add some comments in code and also on github to try explain the code changes

File: src/common/AdaptiveStream.cpp (hunk 2 above)
Comment (glennguy) [reply src/common/AdaptiveStream.cpp:750]: yes the scenario makes sense why it fails. We could try a hacky workaround until something better comes along - assume when the next segment comes it will be the same size (usually is) and add that PTS to current segment's start PTS. Sound good or not?

File: src/common/AdaptiveStream.cpp (hunk 5 above)
Comment (glennguy) [reply src/common/AdaptiveStream.cpp:1256]: Good find!

**Review by glennguy — APPROVED** [review]
Thanks so much for this work and fixing some of the issues in adaptivestream.

File: src/common/AdaptiveStream.cpp (hunk 2 above)
Comment (CastagnaIT) [reply src/common/AdaptiveStream.cpp:750]: i understood but as you said its hacky im not 100% sure that could be so good

i found this problem even when trying to fix bugs to make this live sample playable
https://livesim.dashif.org/livesim/periods_20/testpic_2s/Manifest.mpd

This live sample have periods but no new segments provided,
then its required the use of "InsertLiveSegment" in conjuction with the manifest update worker.
This sample somewhat works on kodi <=v20 because of old code hacks and periods seem "ignored",
on kodi 21 is ofc broken, from what i see seem there are multiple problems on  `CDashTree::RefreshLiveSegments` that seem dont take in account of "inserted" segments on timeline, delete them all and so seem to loose the last inserted segment with the updated pts (because you have to take in account that the downloaded updated manifest dont provide new segments), this will make problems with `AdaptiveStream::ensureSegment` that its not able to find next segment, `AdaptiveStream::start_stream` have problem when switch period, and also with `CSession::OnSegmentChangedRead` that its not able to insert new segments anymore
(these problems may be also similar with https://github.com/xbmc/inputstream.adaptive/issues/1461)
