### PR TITLE
[FragmentedSampleReader] Handle piff protection scheme

### LINKED ISSUE #1181: N€tflix videos VP9 Profile 2 or AV1 cause DecryptAndDecodeVideo error status 5 (kDecodeError)
### Describe the bug
Here is a clear and concise description of what the problem is:

im testing AV1 and VP9 Profile 2 on kodi 21

video with VP9 Profile 2 do not start, and raise a non ending errors of:
`AddOnLog: inputstream.adaptive: WV_CencSingleSampleDecrypter::DecryptAndDecodeVideo: Returned CDM status: 5`
status 5 == kDecodeError

video with AV1 codec video starts, for some minutes i think because firsts unencrypted segments, then raise
`AddOnLog: inputstream.adaptive: WV_CencSingleSampleDecrypter::LogDecryptError: Decrypt failed with error: 2 and key: 0000000006E9C0010000000000000000`

video with AV1 codec video, if seek forward immediately to middle of video, then raise the same above
`AddOnLog: inputstream.adaptive: WV_CencSingleSampleDecrypter::DecryptAndDecodeVideo: Returned CDM status: 5`

Try to play the same VP9 Profile 2 stream **on Kodi 19 works** without problems
apparently a regression somewhere

i have not tested force trying AV1 on Kodi 19 since its not supported

sidenote:
we should limits CDM errors and stop playback without having a infinite loop

### To Reproduce

to test VP9 Profile 2:
1. Install N€tflix addon by using this mod: [plugin.video.netflix_1.20.8+matrix.1_20230302_VP9.2.zip](https://github.com/xbmc/inputstream.adaptive/files/10872186/plugin.video.netflix_1.20.8%2Bmatrix.1_20230302_VP9.2.zip)
2. Ensure that on nf addon expert settings there is VP9 enabled and all other video codecs disabled
3. i dont know if there are more videos with this codec but for sure this, find the movie: `Cosmos Laundromat: First Cycle`
4. play it

to test AV1:
1. Ensure that on nf addon expert settings there is AV1 enabled and all other video codecs disabled
2. Play "Dune" video title

On kodi 19 is played but wrong displayed is expected, ok Kodi 20/21 give error

### Debuglog

The debuglog can be found here:
VP9.2: [kodi.log.txt](https://github.com/xbmc/inputstream.adaptive/files/10872500/kodi.log.txt)

AV1 from starts: [kodi - AV1fromStarts.log.txt](https://github.com/xbmc/inputstream.adaptive/files/10872629/kodi.-.AV1fromStarts.log.txt)
AV1 immediate seek forward: [kodi - AV1skipToMiddle.log.txt](https://github.com/xbmc/inputstream.adaptive/files/10872636/kodi.-.AV1skipToMiddle.log.txt)

### MPD/M3U8s/ISM

An example or copy of a manifest (or manifests for HLS - master and variants) can be found here:
[manifest.mpd.txt](https://github.com/xbmc/inputstream.adaptive/files/10872152/manifest.mpd.txt)
[manifestAV1.mpd.txt](https://github.com/xbmc/inputstream.adaptive/files/10872666/manifestAV1.mpd.txt)

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

i tried apply PR #1165 but has not fixed the problem

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] OSX
 - [x] Windows
 - [ ] Windows UWP

 - Operating system version/name: Windows 11
 - Kodi version: Kodi 21 master branch
 - inputstream.adaptive version: Omega branch 

*note: Once the issue is made we require you to update it with new information should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

### PR DESCRIPTION
**Pull request by CastagnaIT**
## Description

Fix unhandled piff protection scheme used by n€tflix for AV1 and VP9 Profile 2 streams

## Motivation and context

fix #1181

## How has this been tested?

see #1181

## Types of change

- [x] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [ ] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **None of the above** (please explain below)

## Checklist:

- [x] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [x] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [ ] My change requires a change to the Wiki documentation
- [ ] I have updated the documentation accordingly

### CODE REVIEW

File: src/samplereader/FragmentedSampleReader.cpp [hunk 1]
```diff
@@ -425,12 +425,15 @@ AP4_Result CFragmentedSampleReader::ProcessMoof(AP4_ContainerAtom* moof,
...
+      if (schemeType == AP4_PROTECTION_SCHEME_TYPE_CENC ||
+          schemeType == AP4_PROTECTION_SCHEME_TYPE_PIFF ||
+          schemeType == AP4_PROTECTION_SCHEME_TYPE_CBCS)
       {
         m_readerCryptoInfo.m_cryptBlocks = sample_table->GetCryptByteBlock();
         m_readerCryptoInfo.m_skipBlocks = sample_table->GetSkipByteBlock();
 
-        if (schemeType == AP4_PROTECTION_SCHEME_TYPE_CENC)
+        if (schemeType == AP4_PROTECTION_SCHEME_TYPE_CENC ||
+            schemeType == AP4_PROTECTION_SCHEME_TYPE_PIFF)
```
Comment (matthuisman) [inline src/samplereader/FragmentedSampleReader.cpp:436]: Just out of curiosity. Viewing on my phone and notice there is no check for CBCS here vs the other places. Just wanted to make sure this isn't an oversight

Comment (CastagnaIT) [reply src/samplereader/FragmentedSampleReader.cpp:436]: its right because cbcs use AES_CBC

**Review by glennguy — APPROVED** [review]
