### PR TITLE
AdaptiveTree methods cleanups and fix period change for HLS case

### LINKED ISSUE #1551: [HLS] regression, broken audio/subtitle stream on chapter seek
### Describe the bug
Here is a clear and concise description of what the problem is:

When you seek 2 times to a different chapter/period and you change e.g. audio track
audio stream will be broken

use case example with HLS VOD stream with multiple periods (like D+):
1) seek to next period/chapter
2) seek to initial (previous) chapter
3) change audio track
4) the audio track will not works because manifest has been never downloaded
this because has been set to all (whether they are actively in use or not) AdaptiveStream's the PERIOD_CHANGE event status and so dont trigger the STREAM_START:

https://github.com/xbmc/inputstream.adaptive/blob/0e0820d5a91936a7ca5d953c0f7ad2bd0dce8c0f/src/Session.cpp#L944-L949

Allow PrepareRepresentation to be called on PERIOD_CHANGE event to try "fix" this, is also not so good solution
will results in a doubled manifest download, that on malformed live manifests it can cause more side effects, and also doesn't make much sense since the playlists are already updated by the "worker"

i was working to a fix, but since require different changes and much more time to make tests
since my first attempt to do this has failed
i opened this issue to track it and remind this problem

## Possible Fix

create a new EVENT_TYPE as PERIOD_CHANGE_SEEK

or another solution

would be set the PERIOD_CHANGE event only to currently is use AdaptiveStream's (CStream ID's)
so that unused streams will preserve the STREAM_START event and can trigger PrepareRepresentation with STREAM_START

### Debuglog

The debuglog can be found here:

### MPD/M3U8s/ISM

An example or copy of a manifest (or manifests for HLS - master and variants) can be found here:
Use D+ or another HLS stream that have multiple periods and audio tracks

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: --
 - Kodi version: 21
 - inputstream.adaptive version: master

*note: Once the issue is made we require you to update it with new information should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

### LINKED ISSUE #1563: Stop playback again in the event of commercial breaks or X-discontinuity with the inputstream.adaptive addon
### Describe the bug
Here is a clear and concise description of what the problem is:
Hi @CastagnaIT I noticed that the stream from DAZN Darts x PlutoTV simply stops in the event of commercial breaks and you end up back in the Kodi main menu again. 

## Expected Behavior
Here is a clear and concise description of what was expected to happen:
The stream should run through without stopping in the event of commercial breaks.

## Actual Behavior

The stream from DAZN Darts x PlutoTV simply stops in the event of commercial breaks and ends up back in the Kodi main menu.

### To Reproduce

1. Start Kodi
2. Play Stream: https://r.mjh.nz/PlutoTV/64b67f0424ade50008a3be17-alt.m3u8 with IPTV Simple Client (with activated option to use HLS streams via the inputstream.adaptive Addon under "Advanced")

### Debuglog

The debuglog can be found here:

[kodi_dazn_darts_debug.log](https://github.com/xbmc/inputstream.adaptive/files/15415715/kodi_dazn_darts_debug.log)
[manifest_1716460844_master.txt](https://github.com/xbmc/inputstream.adaptive/files/15415717/manifest_1716460844_master.txt)
[manifest_1716460846_child-video.txt](https://github.com/xbmc/inputstream.adaptive/files/15415718/manifest_1716460846_child-video.txt)
[manifest_1716460848_child-video.txt](https://github.com/xbmc/inputstream.adaptive/files/15415719/manifest_1716460848_child-video.txt)
[manifest_1716460854_child-video.txt](https://github.com/xbmc/inputstream.adaptive/files/15415720/manifest_1716460854_child-video.txt)
[manifest_1716460859_child-video.txt](https://github.com/xbmc/inputstream.adaptive/files/15415721/manifest_1716460859_child-video.txt)
[manifest_1716460864_child-video.txt](https://github.com/xbmc/inputstream.adaptive/files/15415722/manifest_1716460864_child-video.txt)
[manifest_1716460869_child-video.txt](https://github.com/xbmc/inputstream.adaptive/files/15415723/manifest_1716460869_child-video.txt)
[manifest_1716460875_child-video.txt](https://github.com/xbmc/inputstream.adaptive/files/15415724/manifest_1716460875_child-video.txt)
[manifest_1716460880_child-video.txt](https://github.com/xbmc/inputstream.adaptive/files/15415725/manifest_1716460880_child-video.txt)
[manifest_1716460886_child-video.txt](https://github.com/xbmc/inputstream.adaptive/files/15415726/manifest_1716460886_child-video.txt)
[manifest_1716460891_child-video.txt](https://github.com/xbmc/inputstream.adaptive/files/15415727/manifest_1716460891_child-video.txt)
[manifest_1716460897_child-video.txt](https://github.com/xbmc/inputstream.adaptive/files/15415728/manifest_1716460897_child-video.txt)
[manifest_1716460903_child-video.txt](https://github.com/xbmc/inputstream.adaptive/files/15415729/manifest_1716460903_child-video.txt)
[manifest_1716460908_child-video.txt](https://github.com/xbmc/inputstream.adaptive/files/15415730/manifest_1716460908_child-video.txt)
[manifest_1716460915_child-video.txt](https://github.com/xbmc/inputstream.adaptive/files/15415731/manifest_1716460915_child-video.txt)
[manifest_1716460921_child-video.txt](https://github.com/xbmc/inputstream.adaptive/files/15415732/manifest_1716460921_child-video.txt)
[manifest_1716460926_child-video.txt](https://github.com/xbmc/inputstream.adaptive/files/15415733/manifest_1716460926_child-video.txt)
[manifest_1716460931_child-video.txt](https://github.com/xbmc/inputstream.adaptive/files/15415734/manifest_1716460931_child-video.txt)
[manifest_1716460936_child-video.txt](https://github.com/xbmc/inputstream.adaptive/files/15415735/manifest_1716460936_child-video.txt)
[manifest_1716460940_child-video.txt](https://github.com/xbmc/inputstream.adaptive/files/15415736/manifest_1716460940_child-video.txt)
[manifest_1716460945_child-video.txt](https://github.com/xbmc/inputstream.adaptive/files/15415737/manifest_1716460945_child-video.txt)
[manifest_1716460950_child-video.txt](https://github.com/xbmc/inputstream.adaptive/files/15415738/manifest_1716460950_child-video.txt)
[manifest_1716460955_child-video.txt](https://github.com/xbmc/inputstream.adaptive/files/15415739/manifest_1716460955_child-video.txt)
[manifest_1716460960_child-video.txt](https://github.com/xbmc/inputstream.adaptive/files/15415740/manifest_1716460960_child-video.txt)
[manifest_1716460966_child-video.txt](https://github.com/xbmc/inputstream.adaptive/files/15415741/manifest_1716460966_child-video.txt)
[manifest_1716460971_child-video.txt](https://github.com/xbmc/inputstream.adaptive/files/15415742/manifest_1716460971_child-video.txt)
[manifest_1716460976_child-video.txt](https://github.com/xbmc/inputstream.adaptive/files/15415743/manifest_1716460976_child-video.txt)
[manifest_1716460983_child-video.txt](https://github.com/xbmc/inputstream.adaptive/files/15415744/manifest_1716460983_child-video.txt)
[manifest_1716460989_child-video.txt](https://github.com/xbmc/inputstream.adaptive/files/15415745/manifest_1716460989_child-video.txt)
[manifest_1716460994_child-video.txt](https://github.com/xbmc/inputstream.adaptive/files/15415746/manifest_1716460994_child-video.txt)

### MPD/M3U8s/ISM

An example or copy of a manifest (or manifests for HLS - master and variants) can be found here:
https://r.mjh.nz/PlutoTV/64b67f0424ade50008a3be17-alt.m3u8

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [X] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] OSX
 - [x] Windows
 - [ ] Windows UWP

 - Operating system version/name: Android 10 / Windows 10
 - Kodi version: 21.0
 - inputstream.adaptive version: inputstream.adaptive v21.4.8

*note: Once the issue is made we require you to update it with new information should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

### PR DESCRIPTION
**Pull request by CastagnaIT**
## Description

Commit 1:
Just cleanups without functional changes, the more noticeable change is that has been decoupled `AdaptiveTree::PrepareRepresentation` with the new `AdaptiveTree::OnStreamChange`. The other methods have been renamed to give more evidence that they are callbacks

Commit 2:
- Partially revert code introduced with PR #1518 about `EVENT_TYPE::PERIOD_CHANGE` and `AdaptiveStream::SetStartEvent`, set period change state to streams turned out to be more problematic than i thought it would be, the current handling of periods and change periods and how streams are initialized makes things too messy and complex, at least I couldn't find a decent way to keep `EVENT_TYPE::PERIOD_CHANGE` state. So as "generic" solution i re-used `AdaptiveTree::m_nextPeriod` to identify a transition state for period changing.
- By re-using `AdaptiveTree::m_nextPeriod` to identify a transition state for period changing, has allowed to remove `m_checkChapterSeek` state from main.cpp
- I have removed also `CRepresentation::IsNeedsUpdates` and `CRepresentation::SetIsNeedsUpdates` that imo its not more needed keep saved this additional state (hoping i haven't missed any particular use cases...)
- I have add to AdaptiveTree the new `m_isReqPrepareStream` config (in similar way of `m_isTTMLTimeRelative`), allows you to configure the parser if it requires the use of `CSession::PrepareStream` to prepare streams, without having hardcoded `TreeType::HLS` condition

## Motivation and context

fix #1551
fix #1563

## How has this been tested?

played D+movies
sequence to replicate period seek problem:

1) seek to next period/chapter
2) seek to initial (previous) chapter
3) change audio track
4) the audio track before was not working because manifest was never downloaded

## Types of change

- [x] **Bug fix** (non-breaking change which fixes an issue)
- [x] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [ ] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **None of the above** (please explain below)

## Checklist:

- [ ] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [ ] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [ ] My change requires a change to the Wiki documentation
- [ ] I have updated the documentation accordingly

### CODE REVIEW

File: src/Session.cpp [hunk 1]
```diff
@@ -933,18 +929,19 @@ void CSession::UpdateStream(CStream& stream)
...
 
   CRepresentation* repr = stream->m_adStream.getRepresentation();
   const EVENT_TYPE startEvent = stream->m_adStream.GetStartEvent();
 
-  // Download the manifest only at first start of the stream
-  if (startEvent == EVENT_TYPE::STREAM_START)
+  // Prepare the representation when the period change usually its not needed,
+  // because the timeline is always already updated
+  if ((!m_adaptiveTree->IsChangingPeriod() || !repr->HasSegmentTimeline()) &&
+      (startEvent == EVENT_TYPE::STREAM_START || startEvent == EVENT_TYPE::STREAM_ENABLE))
```
Comment (CastagnaIT) [inline src/Session.cpp:941]: just a note for `!repr->HasSegmentTimeline()` condition, this imo should not be needed, at least not for HLS where multiple periods have the exact same streams to continue. I don't know how to explain myself well i try, kodi can call `CInputStreamAdaptive::OpenStream` with a stream ID that it decides itself and we cannot predict (language configs, audio configs, etc...), so in the remote case that a stream X in a certain language is not available on the next period, kodi core will probably select an alternative stream language with a different ID, therefore despite IsChangingPeriod is true, we still need to prepare the stream, since should not have the timeline

Comment (glennguy) [reply src/Session.cpp:941]: Yes this shouldn't happen with HLS since we get the master m3u8 once and once only, the variants will never change and are same across all periods, however some could possibly end earlier than others in the case of a live stream (but why would they...)
For DASH anything can happen in a new period and so I think your thinking is correct and the check is valid. Ads would be a good example. They might not carry the same language tracks as the main program content.

Comment (CastagnaIT) [reply src/Session.cpp:941]: also i found another use case for this,
in case the requested video stream ID for some reason goes error as in the example below, Kodi core will try to call all subsequent streams until it finds one that works
```
2024-05-22 18:20:40.425 T:24788   debug <general>: AddOnLog: inputstream.adaptive: GetStreamIds()
2024-05-22 18:20:40.425 T:24788   debug <general>: AddOnLog: inputstream.adaptive: GetStream(3001)
2024-05-22 18:20:40.426 T:24788   debug <general>: AddOnLog: inputstream.adaptive: GetStream(3002)
2024-05-22 18:20:40.427 T:24788   debug <general>: AddOnLog: inputstream.adaptive: GetStream(3003)
2024-05-22 18:20:40.427 T:24788   debug <general>: AddOnLog: inputstream.adaptive: GetStream(3004)
2024-05-22 18:20:40.428 T:24788   debug <general>: AddOnLog: inputstream.adaptive: GetStream(3005)
2024-05-22 18:20:40.428 T:24788   debug <general>: AddOnLog: inputstream.adaptive: GetStream(3006)
2024-05-22 18:20:40.429 T:24788   debug <general>: CDVDDemuxClient::RequestStream(): added/updated stream 3001 with codec_id 27
2024-05-22 18:20:40.429 T:24788   debug <general>: CDVDDemuxClient::RequestStream(): added/updated stream 3002 with codec_id 27
2024-05-22 18:20:40.430 T:24788   debug <general>: CDVDDemuxClient::RequestStream(): added/updated stream 3003 with codec_id 27
2024-05-22 18:20:40.430 T:24788   debug <general>: CDVDDemuxClient::RequestStream(): added/updated stream 3004 with codec_id 27
2024-05-22 18:20:40.430 T:24788   debug <general>: CDVDDemuxClient::RequestStream(): added/updated stream 3005 with codec_id 27
2024-05-22 18:20:40.430 T:24788   debug <general>: CDVDDemuxClient::RequestStream(): added/updated stream 3006 with codec_id 86018
2024-05-22 18:20:40.438 T:24788    info <general>: Opening stream: 3001 source: 256
2024-05-22 18:20:40.438 T:24788   debug <general>: AddOnLog: inputstream.adaptive: OpenStream(3001)
2024-05-22 18:20:40.440 T:24788   debug <general>: AddOnLog: inputstream.adaptive: GetStream(3001)
2024-05-22 18:20:40.441 T:24788   error <general>: CVideoPlayerVideo::OpenStream: Codec id 27 require extradata.
2024-05-22 18:20:40.441 T:24788 warning <general>: CVideoPlayer::OpenStream - Unsupported stream 3001. Stream disabled.
2024-05-22 18:20:40.441 T:24788    info <general>: Opening stream: 3005 source: 256
2024-05-22 18:20:40.442 T:24788   debug <general>: AddOnLog: inputstream.adaptive: OpenStream(3005)
2024-05-22 18:20:40.448 T:24788   debug <general>: CurlFile::XFILE::CCurlFile::Open - <https://
2024-05-22 18:20:40.629 T:24788   debug <general>: AddOnLog: inputstream.adaptive: Download finished: https://
2024-05-22 18:20:40.631 T:24788   debug <general>: AddOnLog: inputstream.adaptive: Manifest saved to: D:\KodiPortable_Builded_20\portable_data\userdata\addon_data\inputstream.adaptive\manifests\manifest_1716394840_child-video.txt
2024-05-22 18:20:40.633 T:24788   debug <general>: AddOnLog: inputstream.adaptive: GetStream(3005)
2024-05-22 18:20:40.633 T:24788   error <general>: CVideoPlayerVideo::OpenStream: Codec id 27 require extradata.
2024-05-22 18:20:40.634 T:24788 warning <general>: CVideoPlayer::OpenStream - Unsupported stream 3005. Stream disabled.
2024-05-22 18:20:40.634 T:24788    info <general>: Opening stream: 3002 source: 256
2024-05-22 18:20:40.634 T:24788   debug <general>: AddOnLog: inputstream.adaptive: OpenStream(3002)
2024-05-22 18:20:40.639 T:24788   debug <general>: CurlFile::XFILE::CCurlFile::Open - <https://
2024-05-22 18:20:40.989 T:24788   debug <general>: AddOnLog: inputstream.adaptive: Download finished: https://
2024-05-22 18:20:40.995 T:24788   debug <general>: AddOnLog: inputstream.adaptive: Manifest saved to: D:\KodiPortable_Builded_20\portable_data\userdata\addon_data\inputstream.adaptive\manifests\manifest_1716394840_child-video_1.txt
2024-05-22 18:20:41.002 T:24788   debug <general>: AddOnLog: inputstream.adaptive: GetStream(3002)
2024-05-22 18:20:41.003 T:24788   error <general>: CVideoPlayerVideo::OpenStream: Codec id 27 require extradata.
2024-05-22 18:20:41.003 T:24788 warning <general>: CVideoPlayer::OpenStream - Unsupported stream 3002. Stream disabled.
2024-05-22 18:20:41.004 T:24788    info <general>: Opening stream: 3003 source: 256
2024-05-22 18:20:41.004 T:24788   debug <general>: AddOnLog: inputstream.adaptive: OpenStream(3003)
2024-05-22 18:20:41.016 T:24788   debug <general>: CurlFile::XFILE::CCurlFile::Open - <https://
2024-05-22 18:20:41.385 T:24788   debug <general>: AddOnLog: inputstream.adaptive: Download finished: https://
2024-05-22 18:20:41.387 T:24788   debug <general>: AddOnLog: inputstream.adaptive: Manifest saved to: D:\KodiPortable_Builded_20\portable_data\userdata\addon_data\inputstream.adaptive\manifests\manifest_1716394841_child-video.txt
2024-05-22 18:20:41.391 T:24788   debug <general>: AddOnLog: inputstream.adaptive: GetStream(3003)
2024-05-22 18:20:41.391 T:24788   error <general>: CVideoPlayerVideo::OpenStream: Codec id 27 require extradata.
2024-05-22 18:20:41.391 T:24788 warning <general>: CVideoPlayer::OpenStream - Unsupported stream 3003. Stream disabled.
2024-05-22 18:20:41.391 T:24788    info <general>: Opening stream: 3004 source: 256
2024-05-22 18:20:41.391 T:24788   debug <general>: AddOnLog: inputstream.adaptive: OpenStream(3004)
2024-05-22 18:20:41.395 T:24788   debug <general>: CurlFile::XFILE::CCurlFile::Open - <https://
2024-05-22 18:20:41.747 T:24788   debug <general>: AddOnLog: inputstream.adaptive: Download finished: https://
2024-05-22 18:20:41.749 T:24788   debug <general>: AddOnLog: inputstream.adaptive: Manifest saved to: D:\KodiPortable_Builded_20\portable_data\userdata\addon_data\inputstream.adaptive\manifests\manifest_1716394841_child-video_1.txt
2024-05-22 18:20:41.751 T:24788   debug <general>: AddOnLog: inputstream.adaptive: GetStream(3004)
2024-05-22 18:20:41.752 T:24788   error <general>: CVideoPlayerVideo::OpenStream: Codec id 27 require extradata.
2024-05-22 18:20:41.752 T:24788 warning <general>: CVideoPlayer::OpenStream - Unsupported stream 3004. Stream disabled.
2024-05-22 18:20:41.752 T:24788    info <general>: Closing stream player 2
```

**Comment by CastagnaIT** [comment]
@glennguy sounds like you're busy lately, I'm going to move on if you have anything you'd rather change/ask leave a comment for a later time

**Comment by glennguy** [comment]
Thanks @CastagnaIT 
Yes it's hard to get time straight away for IA things recently. I had already reviewed the code in the WIP form and no issues that came to mind for me :)
