### PR TITLE
[HLSTree] Fix wrong range end byte

### LINKED ISSUE #1304: problems with HLS streams from arte.tv
### Describe the bug
Here is a clear and concise description of what the problem is:

VOD streams end or stall after a few seconds.

## Expected Behavior

Streams should play completely.

## Actual Behavior

Streams end after a few seconds.

### To Reproduce

I see this with several add-ons for arte.tv mediathek, e.g. plugin.video.artemediathek and plugin.video.tyl0re.arte.
In order to investigate I looked up a failing stream's URL and constructed `bron1.strm` from it (sorry, GitHub won't let me upload STRM files):
```
#KODIPROP:inputstream=inputstream.adaptive
#KODIPROP:inputstream.adaptive.manifest_type=hls
https://arte-cmafhls.akamaized.net/am/cmaf-webonly/095000/095800/095842-001-A_VA/230621005738/095842-001-A_VA_XQ.m3u8
```

1. play `bron1.strm` as a local video file
2.  stream starts to play, both video (1929x1080) and audio, ends after 6 seconds (sometimes stalls for a few seconds before play ends)
3.  debug log http://ix.io/4zn8 

As a further experiment I  downloaded the m3u8 to `bron2.m3u8` and converted all relative URLs in it to absolute URLs resulting in
```
#EXTM3U
#EXT-X-VERSION:7
#EXT-X-INDEPENDENT-SEGMENTS

#EXT-X-STREAM-INF:BANDWIDTH=2293168,AVERAGE-BANDWIDTH=1260256,VIDEO-RANGE=SDR,CODECS="avc1.4d401e,mp4a.40.2",RESOLUTION=768x432,FRAME-RATE=25.000,AUDIO="program_audio_0"
https://arte-cmafhls.akamaized.net/am/cmaf-webonly/095000/095800/095842-001-A_VA/230621005738/medias/095842-001-A_v432.m3u8
#EXT-X-STREAM-INF:BANDWIDTH=4115464,AVERAGE-BANDWIDTH=2297984,VIDEO-RANGE=SDR,CODECS="avc1.4d0028,mp4a.40.2",RESOLUTION=1920x1080,FRAME-RATE=25.000,AUDIO="program_audio_0"
https://arte-cmafhls.akamaized.net/am/cmaf-webonly/095000/095800/095842-001-A_VA/230621005738/medias/095842-001-A_v1080.m3u8
#EXT-X-STREAM-INF:BANDWIDTH=3780400,AVERAGE-BANDWIDTH=2055768,VIDEO-RANGE=SDR,CODECS="avc1.4d401f,mp4a.40.2",RESOLUTION=1280x720,FRAME-RATE=25.000,AUDIO="program_audio_0"
https://arte-cmafhls.akamaized.net/am/cmaf-webonly/095000/095800/095842-001-A_VA/230621005738/medias/095842-001-A_v720.m3u8
#EXT-X-STREAM-INF:BANDWIDTH=1531624,AVERAGE-BANDWIDTH=861400,VIDEO-RANGE=SDR,CODECS="avc1.4d401e,mp4a.40.2",RESOLUTION=640x360,FRAME-RATE=25.000,AUDIO="program_audio_0"
https://arte-cmafhls.akamaized.net/am/cmaf-webonly/095000/095800/095842-001-A_VA/230621005738/medias/095842-001-A_v360.m3u8
#EXT-X-STREAM-INF:BANDWIDTH=933280,AVERAGE-BANDWIDTH=562744,VIDEO-RANGE=SDR,CODECS="avc1.42e00d,mp4a.40.2",RESOLUTION=384x216,FRAME-RATE=25.000,AUDIO="program_audio_0"
https://arte-cmafhls.akamaized.net/am/cmaf-webonly/095000/095800/095842-001-A_VA/230621005738/medias/095842-001-A_v216.m3u8

#EXT-X-I-FRAME-STREAM-INF:BANDWIDTH=1130600,AVERAGE-BANDWIDTH=322720,VIDEO-RANGE=SDR,CODECS="avc1.4d401e",RESOLUTION=768x432,URI="https://arte-cmafhls.akamaized.net/am/cmaf-webonly/095000/095800/095842-001-A_VA/230621005738/medias/095842-001-A_v432_iframe_index.m3u8"
#EXT-X-I-FRAME-STREAM-INF:BANDWIDTH=2522568,AVERAGE-BANDWIDTH=520808,VIDEO-RANGE=SDR,CODECS="avc1.4d0028",RESOLUTION=1920x1080,URI="https://arte-cmafhls.akamaized.net/am/cmaf-webonly/095000/095800/095842-001-A_VA/230621005738/medias/095842-001-A_v1080_iframe_index.m3u8"
#EXT-X-I-FRAME-STREAM-INF:BANDWIDTH=2167640,AVERAGE-BANDWIDTH=514368,VIDEO-RANGE=SDR,CODECS="avc1.4d401f",RESOLUTION=1280x720,URI="https://arte-cmafhls.akamaized.net/am/cmaf-webonly/095000/095800/095842-001-A_VA/230621005738/medias/095842-001-A_v720_iframe_index.m3u8"
#EXT-X-I-FRAME-STREAM-INF:BANDWIDTH=751280,AVERAGE-BANDWIDTH=215752,VIDEO-RANGE=SDR,CODECS="avc1.4d401e",RESOLUTION=640x360,URI="https://arte-cmafhls.akamaized.net/am/cmaf-webonly/095000/095800/095842-001-A_VA/230621005738/medias/095842-001-A_v360_iframe_index.m3u8"
#EXT-X-I-FRAME-STREAM-INF:BANDWIDTH=243384,AVERAGE-BANDWIDTH=87784,VIDEO-RANGE=SDR,CODECS="avc1.42e00d",RESOLUTION=384x216,URI="https://arte-cmafhls.akamaized.net/am/cmaf-webonly/095000/095800/095842-001-A_VA/230621005738/medias/095842-001-A_v216_iframe_index.m3u8"

#EXT-X-MEDIA:TYPE=AUDIO,GROUP-ID="program_audio_0",LANGUAGE="de",NAME="VA",AUTOSELECT=YES,DEFAULT=YES,URI="https://arte-cmafhls.akamaized.net/am/cmaf-webonly/095000/095800/095842-001-A_VA/230621005738/medias/095842-001-A_aud_VA-ALL_1.m3u8"

#SPRITES: https://arte-cmafhls.akamaized.net/am/cmaf-webonly/095000/095800/095842-001-A_VA/230621005738/medias/095842-001-A_SPR.vt
```
1. created another STRM file `bron2.strm` 
```
#KODIPROP:inputstream=inputstream.adaptive
#KODIPROP:inputstream.adaptive.manifest_type=hls
bron2.m3u8
```
2. play `bron2.strm` as local video
3. stream plays completely, but video is 768x432 (i.e. the first variant) and **no** audio
4. debug log http://ix.io/4zn9

### MPD/M3U8s/ISM

An example or copy of a manifest (or manifests for HLS - master and variants) can be found here:
https://arte-cmafhls.akamaized.net/am/cmaf-webonly/095000/095800/095842-001-A_VA/230621005738/095842-001-A_VA_XQ.m3u8

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [x] Linux
 - [ ] OSX
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: LibreELEC 12 (head), RPi4
 - Kodi version: 21.0a2-Omega
 - inputstream.adaptive version: 21.1.2-Omega+ up to 9b70beb

### LINKED ISSUE #1308: [Kodi 21] HLS sample stream has no audio, a regression
### Describe the bug
Here is a clear and concise description of what the problem is:

Look like a regression,
the audio works
on Kodi 19 (perfect audio/video)
on Kodi 20 (slightly corrupted video pixellization, audio ok)
on Kodi 21 works only before the big parsers rework PR, after that PR is broken (video slightly corrupted pixellization)

```
#KODIPROP:inputstream=inputstream.adaptive
#KODIPROP:inputstreamaddon=inputstream.adaptive
#KODIPROP:inputstream.adaptive.manifest_type=hls
https://videojs-test-1.s3.eu-central-1.amazonaws.com/HLS_SingleFiles/master.m3u8
```

also the `ADTSReader` return NONE type
https://github.com/xbmc/inputstream.adaptive/blob/Omega/src/ADTSReader.cpp#L95

but also forcing NONE type to `ParseAac` there is no audio

The log show we have wrong byte ranges
but also by fixing them (i will do PR later) the audio still broken

### Debuglog

The debuglog can be found here:
https://paste.kodi.tv/olexowaniw.kodi

### MPD/M3U8s/ISM

An example or copy of a manifest (or manifests for HLS - master and variants) can be found here:

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] OSX
 - [x] Windows
 - [ ] Windows UWP

 - Operating system version/name: Windows 11
 - Kodi version: Kodi 21
 - inputstream.adaptive version: master branch

*note: Once the issue is made we require you to update it with new information should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

### PR DESCRIPTION
**Pull request by CastagnaIT**
## Description

Fix wrong range end byte, by mistake has been removed with the parser rework

## Motivation and context

fix #1304
and partially fix #1308

## How has this been tested?

playback dont stop after 6 seconds
```
#KODIPROP:inputstream=inputstream.adaptive
#KODIPROP:inputstream.adaptive.manifest_type=hls
https://arte-cmafhls.akamaized.net/am/cmaf-webonly/095000/095800/095842-001-A_VA/230621005738/095842-001-A_VA_XQ.m3u8
```
## Types of change

- [x] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [ ] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **None of the above** (please explain below)

## Checklist:

- [ ] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [ ] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [ ] My change requires a change to the Wiki documentation
- [ ] I have updated the documentation accordingly

### CODE REVIEW

File: src/parser/HLSTree.cpp [hunk 1]
```diff
@@ -348,6 +348,7 @@ PLAYLIST::PrepareRepStatus adaptive::CHLSTree::prepareRepresentation(PLAYLIST::C
         }
 
         newSegment->range_end_ += newSegment->range_begin_;
+        newSegment->range_end_ -= 1;
```
Comment (fritsch) [inline src/parser/HLSTree.cpp]: Why two assignemts here for the same field? Line 350 should be removed?

Comment (glennguy) [reply src/parser/HLSTree.cpp]: No can't be removed, but could be changed to `newSegment->range_end_ += newSegment->range_begin_ - 1;`  instead of adding the new statement. I'm not a good judge of what's more correct or readable, I could go either way.

Comment (CastagnaIT) [reply src/parser/HLSTree.cpp]: right done

**Review by glennguy — APPROVED** [review]

File: src/parser/HLSTree.cpp (hunk 1 above)
Comment (fritsch) [reply src/parser/HLSTree.cpp]: Lol. The "-=" was not visible on my phone. It showed: newSegment->range_end_ = -1; ... Sorry for the noise.
