### PR TITLE
[Subtitles][WebVTT] Sync to current period start (chapter)

### LINKED ISSUE #993: [Disney+] Subtitles appear 3 seconds early
### Describe the bug
Here is a clear and concise description of what the problem is:

NOTE 1: I am not sure where the cause of this issue lies, but @glennguy has asked me to create an issue in the IS:A GitHub (see his reply in this Kodi forum topic: https://forum.kodi.tv/showthread.php?tid=353316&pid=3098252#pid3098252).

NOTE 2: The issue already started with an earlier IS:A version (20.1.2), but was not reported before.

NOTE 3: The issue does **not** happen with the same version of the Disney+ addon with Kodi 19.4 Matrix with the Matrix version of IS:A installed.

When playing some titles with @matthuisman 's Disney+ addon, the subtitles appear exactly 3 seconds early.

Shows that have the issue: Loki, Marvel Studios LEGENDS, The Book of Boba Fett (*)
Shows/movies that don't have the issue: The Mandalorian, Avengers: Infinity War, Buffy the Vampire Slayer

(*) Seems like only newer titles have the issue?

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

The subtitles should appear at the correct time and not 3 seconds early.

## Actual Behavior

Subtitles appear 3 seconds early on some shows.

### To Reproduce

1. Start Kodi v20
2. Open the Disney+ addon
3. Browse a show that has the issue (I used The Book of Boba Fett, Chapter 7)
4. Play the episode

### Debuglog

The debuglog can be found here:
Part 1: https://paste.kodi.tv/ewoqoyajaw.kodi
Part 2: https://paste.kodi.tv/veyequhiho.kodi

### MPD/M3U8s/ISM

An example or copy of a manifest (or manifests for HLS - master and variants) can be found here:

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [X] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: Nvidia Shield Experience 9.0.2 (Android TV 11)
 - Kodi version: kodi-20220517-3d9d2ca5-master-22825-arm64-v8a
 - inputstream.adaptive version: 20.2.0 (the version with the https://github.com/xbmc/inputstream.adaptive/pull/984 included)

*note: Once the issue is made we require you to update it with new information should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

### PR DESCRIPTION
**Pull request by CastagnaIT**
This re-implement the sync to current period start (chapter) for segmented WebVTT
that has been removed after the new webvtt implementation in Kodi core

Fix https://github.com/xbmc/inputstream.adaptive/issues/993

**This depends from** https://github.com/xbmc/xbmc/pull/21523

@glennguy this PR not include your test commit changes,
i think it's best if you do a separate PR to finish the final tune-ups

### CODE REVIEW

File: src/main.cpp [hunk 1]
```diff
@@ -471,13 +482,42 @@ DEMUX_PACKET* CInputStreamAdaptive::DemuxRead(void)
...
+      uint64_t chapterStartTime{m_session->GetChapterStartTime()};
+      p->dts = static_cast<double>(sr->DTS() + chapterStartTime);
+      p->pts = static_cast<double>(sr->PTS() + chapterStartTime);
       p->duration = static_cast<double>(sr->GetDuration());
       p->iStreamId = sr->GetStreamId();
       p->iGroupId = 0;
       p->iSize = iSize;
       memcpy(p->pData, pData, iSize);
+
+      if (sr->GetStreamType() == INPUTSTREAM_TYPE::INPUTSTREAM_TYPE_SUBTITLE &&
```
Comment (glennguy) [inline src/main.cpp]: I was thinking that here we could put most of this into the sample reader itself to keep this function generic to all sample readers.
i.e
```
p->pSideData = sr->GetSideData(chapterStartTime); // or even if we can keep the chapter starting time on the sample reader when we construct/initialize it?
if (p->SideData)
  p->iSideDataElems = 1;
```
And do all the rest on sr - thoughts?

Comment (CastagnaIT) [reply src/main.cpp]: maybe yes i will try do it

Comment (CastagnaIT) [reply src/main.cpp]: done much better less changes

Comment (glennguy) [reply src/main.cpp]: Looks great. I was wrong with the idea about setting chapterstarttime on construction - periods and starting times can change during playback.

**Review by glennguy — APPROVED** [review]

**Comment by glennguy** [comment]
@CastagnaIT I will create PR soon with other sub fixes. Just one more problem to work out.
